apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-lab4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-lab4
  template:
    metadata:
      labels:
        app: deployment-lab4
    spec:
      containers:
        - name: frontend
          image: ifilyaninitmo/itdt--frontend:master
          ports:
          - containerPort: 3000
          env:
            - name: REACT_APP_USERNAME
              value: "Kavabanga"
            - name: REACT_APP_COMPANY_NAME
              value: "OOO-Kavabanga"